include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - pubspec.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
